DEPLOY_ENV: test

#redis config：使用predixy代理访问redis集群
spring:
  redis:
    host: 192.168.1.5
    port: 6379
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/seed
  datasource:
    url: jdbc:mysql://cdb-engax7fq.cd.tencentcdb.com:10013/seed?useUnicode=true&characterEncoding=utf-8
    username: tecent
    password: yixiaoshuang!

log:
  dir: /users/xiaoshuangyi/logs/micro-seed